// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASx6SOC2ogbT6bbG3a2cbhXiA-5GdDWGU',
    appId: '1:680246572599:web:6bfabaf1aa8cc4649d31b2',
    messagingSenderId: '680246572599',
    projectId: 'crudtutorial-899ae',
    authDomain: 'crudtutorial-899ae.firebaseapp.com',
    storageBucket: 'crudtutorial-899ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrH-t8zv3X7El5Gv3_mkwN_32TM0py8S8',
    appId: '1:680246572599:android:4bd7f88127e978189d31b2',
    messagingSenderId: '680246572599',
    projectId: 'crudtutorial-899ae',
    storageBucket: 'crudtutorial-899ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-N2__q1kVA_5M4rRtXt0CTIssdXRwGUE',
    appId: '1:680246572599:ios:608fe476320c04f39d31b2',
    messagingSenderId: '680246572599',
    projectId: 'crudtutorial-899ae',
    storageBucket: 'crudtutorial-899ae.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
